# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.


# Example 1:

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:

# Input: s = "", t = "y"
# Output: "y"

# ---------------------------------------Runtime 43 ms Beats 47.34% Memory 16.3 MB Beats 76.19%---------------------------------------


from collections import Counter


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s_map, t_map = Counter(s), Counter(t)

        res = (s_map - t_map) or (t_map - s_map)
        return list(res.keys()).pop()
